LaFolleAgenceBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: LaFolleAgenceBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: '40'
        authorEmail:
            type: string
            length: '50'
            column: author_email
        title:
            type: string
            length: '150'
        content:
            type: text
        date:
            type: datetime
        approved:
            type: boolean
        my_answer:
            type: text
            nullable: TRUE

    manyToOne:
        post:
            targetEntity: Post
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
