post_index:
    path:     /
    defaults: { _controller: "LaFolleAgenceBundle:Post:index" }
    methods:  GET

post_show:
    path:     /show/{id}
    defaults: { _controller: "LaFolleAgenceBundle:Post:show" }
    methods:  GET

post_new:
    path:     /new
    defaults: { _controller: "LaFolleAgenceBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "LaFolleAgenceBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "LaFolleAgenceBundle:Post:delete" }
    methods:  DELETE
