MigrationBundle\Entity\WpTerms:
    type: entity
    table: wp_terms
    repositoryClass: MigrationBundle\Repository\WpTermsRepository
    indexes:
        slug:
            columns:
                - slug
        name:
            columns:
                - name
    id:
        termId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: term_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                default: ''
        slug:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                default: ''
        termGroup:
            type: bigint
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: term_group
    lifecycleCallbacks: {  }
