la_folle_agence_homepage:
    path:     /
    defaults: { _controller: LaFolleAgenceBundle:Default:index }

la_folle_agence_lafolleagence:
    resource: "@LaFolleAgenceBundle/Resources/config/routing/lafolleagence.yml"
    prefix: /
